### ISSUE TITLE
Cannot be installed on Windows . Is `fitsio` dependency needed?

### ISSUE THREAD

**Issue by orionlee** [tessgi/tesscube#11]
Cannot install the package on Windows due to error in installing `fitsio` (error ""MSVCCompiler has no attribute compiler"", a known issue: https://github.com/esheldon/fitsio/issues/103 )

Is the `fitsio` dependency truly needed? There does not seem to have any direct dependency on it in the codes. What's more, when I remove it from `pyproject.toml` and do a source install, the codes seem to work without it.
https://github.com/tessgi/tesscube/blob/22fd0bb84ea62ac41ae751f425adf3efd1e7b60f/pyproject.toml#L13

Version: 1.0.2dev0
Platform: Windows 11

**Comment by christinahedges** [comment]
Hey @orionlee thanks for finding this! fitsio is not needed, originally I was going to use this to access specific bytes in the fits cubes stored at MAST, but I got around it, I will release a new version with no fitsio dependency thanks for the catch!
